### ISSUE TITLE
Multiple comments in Single cell

### ISSUE THREAD

**Issue by ghost** [matbrady/github-issues-export#1]
@matbrady  How do I get all the comments in a single issues in single cell in csv?

**Comment by matbrady** [comment]
@testkamal
The `json2csv` config value [`unwindPath`](https://www.npmjs.com/package/json2csv#available-options) is responsible for creating multiple rows from repeated field values. 
You could combine all comments into a single cell by modifying the JSON values before they are converted to CSV. I’ve created a feature branch here that demos the updates.

**feature branch:** https://github.com/matbrady/github-issues-export/commit/a13345076caf20d9020d611c392172d0c556f701?diff=split

**Comment by ghost** [comment]
@matbrady  Thanks for the help 👍
