### ISSUE TITLE
Authorization parameter

### ISSUE THREAD

**Issue by ghost** [matbrady/github-issues-export#2]
@matbrady 
Can this script be modified to use ssh as auth parameter? SAML single sign on?

https://github.com/matbrady/github-issues-export/blob/84636d35f4d9899b0e1194f94d55d513f33a7d36/index.js#L66-L70

**Comment by matbrady** [comment]
@testkamal I'm not sure I understand your use case. Any other details?  
The [authorization](https://developer.github.com/v4/guides/forming-calls/#authenticating-with-graphql) is specific to accessing repos associated with a Github account. You'll need to provide a token regardless of the request coming from this script or a separate application. 
It sounds like you're trying to authenticate users prior to submitting the query. In that case, your business logic should come before the request to Github and you shouldn't need to change anything about the authorization headers in the code you referenced above.

**Comment by ghost** [comment]
This is out of my ballpark. Any help is appreciated.

Background -
The GitHub repo is on private server and to clone the repo in my IDE (using
intelliJ) to commit changes, I'm using ssh as authentication. Previously
authorization token worked but as per policy change we have to use ssh and
token is not longer required.

Use scenario - setting up scheduled job to run the script to export the
GitHub issues in csv file. Based on the policy change, how to establish the
authentication to read the GitHub issues?
The URL is same but if I pass the authentication token it doesn't work. I
will try share the failure log.

Thanks

**Comment by matbrady** [comment]
@testkamal unfortunately the Github GraphQL API is only accessible with HTTPS. You could always try contacting [Github's support](https://github.com/contact) to see if there are other options available.
